export const GET_GITHUB_USERS = 'GithubUser/GET_GITHUB_USERS';
export const GET_GITHUB_USERS_FAILURE = 'GithubUser/GET_GITHUB_USERS_FAILURE';
export const GET_GITHUB_USERS_SUCCESS = 'GithubUser/GET_GITHUB_USERS_SUCCESS';