export const GET_GITHUB_USERS = 'GithubUser/GET_GITHUB_USERS';
export const GET_GITHUB_USERS_FAILURE = 'GithubUser/GET_GITHUB_USERS_FAILURE';
export const GET_GITHUB_USERS_SUCCESS = 'GithubUser/GET_GITHUB_USERS_SUCCESS';
export const RESET_GET_GITHUB_USER_STATUS = 'GithubUser/RESET_GET_GITHUB_USER_STATUS';
export const SEARCH_USERNAME_QUERY = 'GithubUser/SEARCH_USERNAME_QUERY';