export const GET_GITHUB_USER_REPOSITORIES = 'GithubRepo/GET_GITHUB_USER_REPOSITORIES';
export const GET_GITHUB_USER_REPOSITORIES_SUCCESS = 'GithubRepo/GET_GITHUB_USER_REPOSITORIES_SUCCESS';
export const GET_GITHUB_USER_REPOSITORIES_FAILURE = 'GithubRepo/GET_GITHUB_USER_REPOSITORIES_FAILURE';

export const GET_USER_REPOSITORY_README_RAW = 'GithubRepo/GET_USER_REPOSITORY_README_RAW';
export const GET_USER_REPOSITORY_README_RAW_SUCCESS = 'GithubRepo/GET_USER_REPOSITORY_README_RAW_SUCCESS';
export const GET_USER_REPOSITORY_README_RAW_FAILURE = 'GithubRepo/GET_USER_REPOSITORY_README_RAw_FAILURE';