export const GET_GITHUB_USER_REPOSITORIES = 'GithubRepo/GET_GITHUB_USER_REPOSITORIES';
export const GET_GITHUB_USER_REPOSITORIES_SUCCESS = 'GithubRepo/GET_GITHUB_USER_REPOSITORIES_SUCCESS';
export const GET_GITHUB_USER_REPOSITORIES_FAILURE = 'GithubRepo/GET_GITHUB_USER_REPOSITORIES_FAILURE';
